# Site
name: "jaswanth.xyz"
title: "jaswanth.xyz"
description: "Jas' blog"
baseurl: ""
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
google_analytics: 'G-04MTXH90WZ'
disqus: 'jaswanth-xyz'
mailchimp-list: # 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title
email: jaswanth.ooty@gmail.com

# Authors
authors:
  jas:
    name: Jaswanth Manigundan
    display_name: Jas
    avatar: 'assets/images/jas.jpg'
    email: jaswanth.ooty@gmail.com
    web: https://www.jaswanth.xyz
    twitter: https://twitter.com/jaswanth_m
    linkedin: https://www.linkedin.com/in/-jaswanth/
    description: I'm a developer turned tester who is very passionate about building quality software..!

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
  - jekyll-youtube
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# # Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
# adsense: "disabled"
# adsense-data-ad-client: "ca-pub-3412143450191416"
# adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
